export const HOME_PAGE_INPUT1_CHANGED = "HOME_PAGE_INPUT1_CHANGED";
export const HOME_PAGE_INPUT2_CHANGED = "HOME_PAGE_INPUT2_CHANGED";
export const P1_DATA_PROCESS_START = "P1_DATA_PROCESS_START";
export const P1_DATA_PROCESS_SUCCESS = "P1_DATA_PROCESS_SUCCESS";
export const P1_DATA_PROCESS_ERROR = "P1_DATA_PROCESS_ERROR";